"""Applies db/migrations/*.sql in order, tracking what has already run so
`make db` is safe to re-run. After applying, regenerates db/schema.sql from
the live database so it can never drift from what migrations actually created.

Run as `python -m app.db.migrate` (DATABASE_PATH from the environment, default
./data/cashflow.db) or call apply_migrations(path) directly, e.g. from tests.
"""

from __future__ import annotations

import os
import sqlite3
from pathlib import Path

from app.db.connection import write_connection

MODULE_DIR = Path(__file__).resolve().parent
MIGRATIONS_DIR = MODULE_DIR / "migrations"
SCHEMA_SQL_PATH = MODULE_DIR / "schema.sql"

_TYPE_ORDER = {"table": 0, "view": 1, "trigger": 2, "index": 3}


def _migration_files() -> list[Path]:
    return sorted(MIGRATIONS_DIR.glob("*.sql"))


def apply_migrations(db_path: str | Path) -> None:
    db_path = Path(db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)

    conn = write_connection(db_path)
    try:
        conn.execute(
            "CREATE TABLE IF NOT EXISTS _migrations "
            "(version TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT (datetime('now')))"
        )
        applied = {
            row[0] for row in conn.execute("SELECT version FROM _migrations").fetchall()
        }

        for path in _migration_files():
            if path.name in applied:
                continue
            conn.executescript(path.read_text(encoding="utf-8"))
            conn.execute(
                "INSERT INTO _migrations (version) VALUES (?)", (path.name,)
            )
            conn.commit()

        _dump_schema(conn)
    finally:
        conn.close()


def _dump_schema(conn: sqlite3.Connection) -> None:
    rows = conn.execute(
        """
        SELECT type, sql FROM sqlite_master
        WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name != '_migrations'
        ORDER BY
          CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END,
          rowid
        """
    ).fetchall()

    header = (
        "-- GENERATED by `make db` (app/db/migrate.py) from the applied migrations\n"
        "-- in app/db/migrations/. Do not hand-edit; add a new migration instead.\n\n"
    )
    body = ";\n\n".join(sql for _type, sql in rows) + ";\n"
    SCHEMA_SQL_PATH.write_text(header + body, encoding="utf-8")


def main() -> None:
    db_path = os.environ.get("DATABASE_PATH", "./data/cashflow.db")
    apply_migrations(db_path)
    print(f"db: applied migrations to {db_path}")


if __name__ == "__main__":
    main()
