-- GENERATED by `make db` (app/db/migrate.py) from the applied migrations
-- in app/db/migrations/. Do not hand-edit; add a new migration instead.

CREATE TABLE business (                 -- one row only: one business per installation
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',
  safety_amount_paise INTEGER NOT NULL CHECK (safety_amount_paise >= 0),
  escalation_stake_paise INTEGER NOT NULL DEFAULT 5000000
    CHECK (escalation_stake_paise >= 0),   -- owner setting, ₹50,000 default
  horizon_days INTEGER NOT NULL DEFAULT 14,
  payment_days TEXT NOT NULL DEFAULT 'MON,THU',
  language TEXT NOT NULL DEFAULT 'en'
);

CREATE TABLE app_user (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL CHECK (role IN ('owner','helper')),
  password_hash TEXT NOT NULL           -- Argon2
);

CREATE TABLE party (                    -- vendors and customers
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  kind TEXT NOT NULL CHECK (kind IN ('vendor','customer','both')),
  name TEXT NOT NULL,
  gstin TEXT,
  aliases_json TEXT NOT NULL DEFAULT '[]',  -- names seen in bank alerts, added only after owner confirms
  bank_account_mask TEXT,
  bank_ifsc TEXT,
  bank_status TEXT NOT NULL DEFAULT 'none'
    CHECK (bank_status IN ('none','verified','change_pending'))
);

CREATE TABLE bank_account (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  bank_name TEXT NOT NULL,
  account_name TEXT NOT NULL,
  account_mask TEXT NOT NULL,
  alert_senders_json TEXT NOT NULL DEFAULT '[]',
  opening_balance_paise INTEGER NOT NULL,
  opening_balance_at TEXT NOT NULL,
  reported_balance_paise INTEGER,
  reported_at TEXT,
  drift_status TEXT NOT NULL DEFAULT 'OK'
    CHECK (drift_status IN ('OK','CHECKING','ASK_OWNER')),
  last_reconciled_at TEXT,
  status TEXT NOT NULL DEFAULT 'active'
);

CREATE TABLE source_document (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  kind TEXT NOT NULL CHECK (kind IN ('email','photo','pdf','voice','typed')),
  external_ref TEXT,                    -- Gmail message ID or upload ID
  content_sha256 TEXT NOT NULL,
  received_at TEXT NOT NULL,
  submitted_by INTEGER REFERENCES app_user(id),
  storage_path TEXT,                    -- encrypted file on disk
  doc_type TEXT,                        -- set by the sort step
  status TEXT NOT NULL DEFAULT 'NEW'
    CHECK (status IN ('NEW','LOCKED','PROCESSED','IRRELEVANT','FAILED')),
  UNIQUE (business_id, content_sha256),
  UNIQUE (business_id, kind, external_ref)
);

CREATE TABLE candidate (
  id INTEGER PRIMARY KEY,
  source_document_id INTEGER NOT NULL REFERENCES source_document(id),
  record_type TEXT NOT NULL
    CHECK (record_type IN ('txn','payable','receivable','tax','statement')),
  payload_json TEXT NOT NULL,
  transcript TEXT,                      -- voice notes only
  model_id TEXT, thinking TEXT, prompt_version TEXT,
  checks_json TEXT,                     -- result of every rule check
  status TEXT NOT NULL
    CHECK (status IN ('NEW','VALID','INVALID','AWAITING_OWNER','ACCEPTED','REJECTED')),
  attempts INTEGER NOT NULL DEFAULT 0,
  created_by TEXT NOT NULL,             -- 'pipeline' or 'agent:case:<id>'
  created_at TEXT NOT NULL
);

CREATE TABLE bank_txn (
  id INTEGER PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES bank_account(id),
  direction TEXT NOT NULL CHECK (direction IN ('debit','credit')),
  amount_paise INTEGER NOT NULL CHECK (amount_paise > 0),
  txn_date TEXT NOT NULL,
  value_date TEXT,
  description TEXT,
  counterparty TEXT,
  party_id INTEGER REFERENCES party(id),
  reference TEXT,
  balance_after_paise INTEGER,          -- available balance in the alert, if shown
  dedup_key TEXT NOT NULL UNIQUE,       -- built by code from account, date, amount, reference
  source_document_id INTEGER REFERENCES source_document(id),
  candidate_id INTEGER REFERENCES candidate(id),
  status TEXT NOT NULL
    CHECK (status IN ('UNMATCHED','MATCHED','EXPLAINED','ADJUSTMENT','REVERSED'))
);

CREATE TABLE payable (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  party_id INTEGER REFERENCES party(id),
  invoice_number TEXT,
  invoice_date TEXT,
  amount_paise INTEGER NOT NULL CHECK (amount_paise > 0),
  due_date TEXT NOT NULL,
  priority TEXT NOT NULL
    CHECK (priority IN ('statutory','critical','normal','flexible')),
  grace_days INTEGER NOT NULL DEFAULT 0,
  discount_paise INTEGER,
  discount_by TEXT,
  parent_payable_id INTEGER REFERENCES payable(id),  -- set on a split
  source_document_id INTEGER REFERENCES source_document(id),
  status TEXT NOT NULL CHECK (status IN
    ('DRAFT','CONFIRMED','PLANNED','PAYMENT_EXPECTED','PAID','REOPENED','REVIEW','SPLIT')),
  planned_date TEXT,
  approved_by INTEGER REFERENCES app_user(id),
  approved_at TEXT,
  matched_txn_id INTEGER REFERENCES bank_txn(id),
  version INTEGER NOT NULL DEFAULT 1   -- optimistic locking
);

CREATE TABLE receivable (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  party_id INTEGER REFERENCES party(id),
  invoice_number TEXT,
  invoice_date TEXT,
  amount_paise INTEGER NOT NULL CHECK (amount_paise > 0),
  due_date TEXT,
  expected_date TEXT,
  confidence TEXT NOT NULL
    CHECK (confidence IN ('CONFIRMED','COMMITTED','EXPECTED','UNKNOWN')),  -- CONFIRMED = received and matched
  matched_txn_id INTEGER REFERENCES bank_txn(id),
  source_document_id INTEGER REFERENCES source_document(id),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE tax_obligation (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  tax_type TEXT NOT NULL CHECK (tax_type IN ('GST','TDS','PF','ESI','ADVANCE_TAX')),
  period TEXT NOT NULL,
  due_date TEXT NOT NULL,
  amount_paise INTEGER,
  amount_status TEXT NOT NULL
    CHECK (amount_status IN ('CONFIRMED','ESTIMATED','MISSING')),
  payable_id INTEGER REFERENCES payable(id),   -- the statutory payable this creates
  challan_document_id INTEGER REFERENCES source_document(id)
);

CREATE TABLE plan_run (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  created_at TEXT NOT NULL,
  triggered_by TEXT NOT NULL,           -- 'monday', 'event:<id>', 'what_if'
  inputs_sha256 TEXT NOT NULL,
  planner_version TEXT NOT NULL,
  opening_cash_paise INTEGER NOT NULL,
  lowest_balance_paise INTEGER NOT NULL,
  lowest_on TEXT NOT NULL,              -- lowest of the full schedule (Planning engine, step 4)
  valid INTEGER NOT NULL CHECK (valid IN (0,1)),
  is_current INTEGER NOT NULL DEFAULT 0
, summary_text TEXT, summary_source TEXT CHECK (summary_source IN ('gemini', 'template')));

CREATE TABLE plan_line (
  plan_run_id INTEGER NOT NULL REFERENCES plan_run(id),
  payable_id INTEGER NOT NULL REFERENCES payable(id),
  decision TEXT NOT NULL CHECK (decision IN ('PAY','WAIT','ESCALATE')),
  pay_on TEXT,
  reason TEXT NOT NULL, amount_paise INTEGER,
  PRIMARY KEY (plan_run_id, payable_id)
);

CREATE TABLE plan_day (
  plan_run_id INTEGER NOT NULL REFERENCES plan_run(id),
  day TEXT NOT NULL,
  balance_paise INTEGER NOT NULL,
  PRIMARY KEY (plan_run_id, day)
);

CREATE TABLE shortfall_option (
  id INTEGER PRIMARY KEY,
  plan_run_id INTEGER NOT NULL REFERENCES plan_run(id),
  kind TEXT NOT NULL CHECK (kind IN
    ('early_receipt','split','delay_flexible','authorise_breach','ask_ca')),
  params_json TEXT NOT NULL,
  lowest_balance_paise INTEGER,
  meets_rule INTEGER NOT NULL CHECK (meets_rule IN (0,1)),
  chosen_by INTEGER REFERENCES app_user(id),
  chosen_at TEXT
);

CREATE TABLE agent_case (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  kind TEXT NOT NULL CHECK (kind IN
    ('unknown_txn','drift','failed_payment','ambiguous_match')),
  subject_ref TEXT NOT NULL,            -- e.g. 'bank_txn:41'
  stake_paise INTEGER NOT NULL,
  thinking TEXT NOT NULL CHECK (thinking IN ('medium','high')),
  steps INTEGER NOT NULL DEFAULT 0,
  validation_failures INTEGER NOT NULL DEFAULT 0,
  case_file_md TEXT NOT NULL,
  escalation_rule TEXT,
  status TEXT NOT NULL
    CHECK (status IN ('OPEN','RESOLVED','ASK_OWNER','CLOSED_BY_OWNER')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, state_json TEXT NOT NULL DEFAULT '{}');

CREATE TABLE job (
  id INTEGER PRIMARY KEY,
  kind TEXT NOT NULL,                   -- one of the job kinds in "Jobs and the document pipeline"
  payload_json TEXT NOT NULL,
  idempotency_key TEXT UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('queued','running','done','failed','dead')),
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  run_after TEXT NOT NULL,
  locked_at TEXT,
  last_error TEXT
);

CREATE TABLE gmail_connection (
  id INTEGER PRIMARY KEY CHECK (id = 1),    -- one mailbox per installation
  email_address TEXT NOT NULL,
  scope TEXT NOT NULL
    CHECK (scope = 'https://www.googleapis.com/auth/gmail.readonly'),
  refresh_token_enc BLOB,                   -- Fernet-encrypted; NULL after disconnect; access tokens are never stored
  status TEXT NOT NULL CHECK (status IN ('CONNECTED','DISCONNECTED')),
  connected_at TEXT NOT NULL,
  disconnected_at TEXT,
  last_error TEXT
);

CREATE TABLE sync_state (
  source TEXT PRIMARY KEY,              -- 'gmail' or 'eml_folder'
  last_synced_at TEXT
);

CREATE TABLE event (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  occurred_at TEXT NOT NULL,
  actor TEXT NOT NULL,                  -- 'owner:3', 'planner', 'reconciler', 'pipeline'
  event_type TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  before_json TEXT,
  after_json TEXT,
  reason TEXT,
  source_ref TEXT,
  trace_run_id TEXT
);

CREATE TABLE plan_override (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  payable_id INTEGER NOT NULL REFERENCES payable(id),
  kind TEXT NOT NULL CHECK (kind IN ('authorise_breach','delay_flexible')),
  shortfall_option_id INTEGER REFERENCES shortfall_option(id),
  floor_paise INTEGER,                  -- authorise_breach: the lowest balance the owner saw (D18)
  breach_on TEXT,                       -- authorise_breach: the day that lowest was shown on
  created_by INTEGER NOT NULL REFERENCES app_user(id),
  created_at TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('ACTIVE','ENDED','LAPSED')),
  ended_at TEXT,
  CHECK (kind <> 'authorise_breach' OR floor_paise IS NOT NULL)
);

CREATE TABLE "owner_question" (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  case_id INTEGER REFERENCES agent_case(id),
  kind TEXT NOT NULL CHECK (kind IN
    ('confirm_record','unlock_pdf','explain_txn','confirm_balance','choose_option',
     'approve_bank_change','reconnect_gmail','ca_reminder','agent_question')),
  body_text TEXT NOT NULL,              -- shown as plain text
  choices_json TEXT,
  answer_json TEXT,
  answered_by INTEGER REFERENCES app_user(id),
  answered_at TEXT,
  status TEXT NOT NULL CHECK (status IN ('OPEN','ANSWERED','EXPIRED'))
);

CREATE TABLE owner_alert (
  id INTEGER PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES business(id),
  kind TEXT NOT NULL CHECK (kind IN ('money_received','payment_failed','unexpected_debit','balance_mismatch')),
  ref TEXT NOT NULL,                    -- 'receivable:3', 'payable:5', 'agent_case:2', 'bank_txn:7', 'bank_account:1'
  created_at TEXT NOT NULL,
  sent_at TEXT
);

CREATE VIEW account_balance AS
SELECT a.id AS account_id,
       a.opening_balance_paise
       + COALESCE(SUM(CASE WHEN t.direction = 'credit' THEN t.amount_paise
                           ELSE -t.amount_paise END), 0) AS calculated_balance_paise
FROM bank_account a
LEFT JOIN bank_txn t
  ON t.account_id = a.id AND t.txn_date >= a.opening_balance_at
  AND t.status <> 'REVERSED'
GROUP BY a.id;

CREATE TRIGGER event_no_update BEFORE UPDATE ON event
  BEGIN SELECT RAISE(ABORT, 'event is append-only'); END;

CREATE TRIGGER event_no_delete BEFORE DELETE ON event
  BEGIN SELECT RAISE(ABORT, 'event is append-only'); END;

CREATE UNIQUE INDEX owner_alert_unsent ON owner_alert (business_id, kind, ref) WHERE sent_at IS NULL;
